#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/Icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : YOU                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A new kind of Journaling Experiance

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Gifton                                
your_link                                 :                    
your_city                                 : Seattle                                
email_address                             : giftondev@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : gift00n
github_username                           : gifton
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Journaling, but everywhere
    description                           : We wanted to minimize time between what you think, and when you record.  Instead of waiting till the end of the day, or a conveniant time to sit with a notebook, open YOU and Voilá!
    fontawesome_icon_name                 : magic
    
  - title                                 : Safe
    description                           : This app does not store your content on any server, for any reason.  Your content stays on your device. Always.
    fontawesome_icon_name                 : lock

  - title                                 : Smarts
    description                           : YOU  was built to help, whenever a new Thought is added YOU will identify keywords in it, and help you find similar Thoughts.
    fontawesome_icon_name                 : brain

  - title                                 : Build relationships
    description                           : Use Sequences to create groups of Thoughts, and use that context to help further your thought progression.
    fontawesome_icon_name                 : sync

  - title                                 : Accessable
    description                           : YOU is built with the intention of making the recording of Thoughts as easy as possible. One-click new Thoughts, Adjustable font sizes and much more!
    fontawesome_icon_name                 : thumbs-up
  
  - title                                 : Progress
    description                           : Improvement always beneifits from the Acknowledgement of progress.  Keep track of what you do in YOU with the Progress page and Thought History feature
    fontawesome_icon_name                 : clock

  - title                                 : Keywords
    description                           : Use Keywords to find Related Thoughts, create unique trails of thought by adding custom Keywords.
    fontawesome_icon_name                 : link

  - title                                 : Explore
    description                           : Easily peruse your thoughts, sorting and filtering with robust options and search through Thoughts, Keywords and Sequences.
    fontawesome_icon_name                 : binoculars

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
